More improvements to tool calling and output handling

diff --git a/shellm b/shellm
--- a/shellm
+++ b/shellm
@@ -9,14 +9,23 @@ VERBOSE=2  # Default Errors, Warnings and Tools
 USE_TOOL=0
 # Global associative array for tools
 declare -A TOOLS=()
-
+PROMPT_FRAGMENT_AGENT=""
 # Global variables for system prompts
 SYSTEM_PROMPT_INSTRUCT="You are Shellm, an intelligent AI assistant designed to process user requests with accuracy and efficiency. Your goal is to provide informative and context-aware responses."
 
 SYSTEM_PROMPT_TOOL='You are a highly intelligent agent responsible for selecting and configuring tools based on user instructions.
+
+You are embedded in an application that allows you to
+* modify files
+* execute code
+* access the internet
+* much, much more
+
 Your mission is to analyze tasks thoroughly and create an effective series of tool calls to deliver optimal results.
-Break down tasks into manageable steps, utilizing multiple tools and crafting a coherent toolchain.
 You may reuse tools in various configurations to ensure the best outcome.
+Break down tasks into manageable steps, utilizing multiple tools and crafting a coherent toolchain.
+You are not alone! Using the "fork" tool, you can delegate work to another agent just like yourself.
+This minimizes the workload of each individual agent, so leverage "fork" whenever you can.
 
 
 # Tool Usage
@@ -49,6 +58,22 @@ You SHOULD prepare the final "say" invocation by letting the LLM create a human-
 You are also encouraged to "say" status updates in longer toolchains.
 '
 
+SYSTEM_PROMPT_TOOL_CONTEXT='You are a highly intelligent agent responsible for analyzing and interpreting user input.
+You are embedded in an application that allows you to
+* modify files
+* execute code
+* access the internet
+* much, much more
+
+You are sitting between the user and a tool calling AI agent. You are a planning expert capable of strategic long-term thinking.
+Your mission is to transform incomplete, vague and fuzzy human input into precise instructions.
+Identify missing or incomplete information.
+Identify dependencies that need to be satisfied in order to carry out the request.
+Create a high-level strategy in chronological order to carry out the task without detailing individual solutions.
+Keep it declarative and let the AI agent pick the concrete tools.
+Hold the prose. Bullet points only.
+'
+
 # Output variables
 SHELLM_OUTPUT=""
 SHELLM_PREVIOUS=""
@@ -56,7 +81,7 @@ SHELLM_ERROR=""
 
 # Function for colored logging with severity levels
 log() {
-  local level="$1"; local message="\e[37m$(echo "$2" | tr '\n' ' ' | cut -c1-500)\e[0m"; local color
+  local level="$1"; local message="\e[37m$(echo "$2" | tr '\n' ' ' )\e[0m"; local color
   case "$level" in
     debug) color="\e[33m[DEBUG]\e[0m" ;;
     tool) color="\e[36m[TOOL]\e[0m" ;;
@@ -64,9 +89,26 @@ log() {
     error) color="\e[31m[ERROR]\e[0m" ;;
     *) color="\e[0m" ;;
   esac
+  [[ $VERBOSE -gt 0 && "$level" == "error" ]] && echo -e "\n$color $message" >&2
   [[ $VERBOSE -gt 1 && "$level" == "warning" ]] && echo -e "\n$color $message" >&2
   [[ $VERBOSE -gt 2 && "$level" == "tool" ]] && echo -e "\n$color $message" >&2
   [[ $VERBOSE -gt 3 && "$level" == "debug" ]] && echo -e "\n$color $message" >&2
+}
+
+# Function to escape input read from stdin
+escape() {
+  # Read from stdin
+  local input
+  input=$(cat)
+
+  # Escape special characters only for command execution, not for user output
+  local escaped_input
+  escaped_input="${input//&/\\&}"  # Escape ampersands
+  escaped_input="${escaped_input//\\/\\\\}"  # Escape backslashes
+  escaped_input="${escaped_input//\/\x27}"  # Escape single quotes
+  escaped_input="${escaped_input//\"/\\\"}"  # Escape double quotes
+  escaped_input="${escaped_input//\`/\\\`}"  # Escape backticks
+  echo "$escaped_input"
 }
 
 # Function to load tools from JSON file
@@ -115,7 +157,8 @@ generate_response() {
   # Capture the output of the streaming request into SHELLM_OUTPUT while streaming it
   curl -sN "$API_URL/generate" \
     -d "{\"model\": \"$MODEL_SMALL\", \"system\": $escaped_system_prompt, \"prompt\": $escaped_prompt, \"stream\": true, \"options\": { \"num_predict\": $num_predict, \"num_ctx\": 4096 } }" | \
-    stdbuf -o0 jq -j '.response // empty'
+    stdbuf -o0 jq -j '.response // empty' | escape
+  echo ""
 }
 
 generate_tool_calls() {
@@ -197,13 +240,13 @@ apply_tool_calls() {
       # Check if escaping is required
       local raw
       raw=$(echo "$tool_def" | jq -r --arg param "$param" '.function.parameters.properties[$param].raw // false')
-      log tool "Parameter: $param, Value: $value, Escape: $raw"
+      log tool "Parameter: $param, Value: $value, Raw: $raw"
       value="${value//&/\\&}"  # Escape ampersands
       # Conditionally escape or pass as-is based on the "escape" field
       if [[ ! "$raw" == "true" ]]; then
         log tool "Escaping parameter: $param"
-        value="${value//\'/\'\"\'\"\'}"  # Escape single quotes
-        value="${value//\`/\\\`}"        # Escape backticks
+        value="$(echo "$value" | escape)"
+
       fi
 
       interpolated_cmd="${interpolated_cmd//\$\{$param\}/$value}"
@@ -216,25 +259,29 @@ apply_tool_calls() {
     log tool "Executing command: $interpolated_cmd"
 
     # Execute the interpolated command, capturing all details
-    # Kudos to madmurphy over at https://stackoverflow.com/a/59592881
-    local exit_code
+    exit_code=0
+
+    # Use a subshell to redirect stdout and stderr
     {
-        IFS=$'\n' read -r -d '' SHELLM_PREVIOUS;
-        IFS=$'\n' read -r -d '' SHELLM_ERROR;
-        (IFS=$'\n' read -r -d '' exit_code; return ${_ERRNO_});
-    } < <((printf '\0%s\0%d\0' "$(((({ eval "$interpolated_cmd"; echo "${?}" 1>&3-; } | tr -d '\0' 1>&4-) 4>&2- 2>&1- | tr -d '\0' 1>&4-) 3>&1- | exit "$(cat)") 4>&1-)" "${?}" 1>&2) 2>&1)
+      SHELLM_PREVIOUS=$(eval "$interpolated_cmd")
+      exit_code=$?
+    } 2> >(SHELLM_ERROR=$(cat) >&2)
+
+    log tool "Exit: $exit_code"
 
     # Check for a nonzero exit code and echo errors if present
     if [[ $exit_code -ne 0 ]]; then
       log error "Command '$interpolated_cmd' failed with exit code $exit_code."
-      echo "$SHELLM_ERROR" >&2
+      log error "$SHELLM_ERROR"
+      # TODO Consider recursion with a fresh prompt to allow the agent to try again
+      exit 1
     else
       log tool "Result: $SHELLM_PREVIOUS"
     fi
 
     # If the tool is "say", echo its output to the terminal
     if [ "$tool_name" == "say" ]; then
-      echo -n "$SHELLM_PREVIOUS"
+      printf '%s' "$SHELLM_PREVIOUS"
       SHELLM_OUTPUT+=$SHELLM_PREVIOUS
     fi
   done
@@ -307,24 +354,31 @@ pull_model() {
   fi
 }
 
+# Function to gather system information
+gather_system_info() {
+  local terminal_info
+  local os_info
+
+  # Gather terminal, hostname, and OS type information
+  terminal_info=$(echo "$TERM")
+  os_info=$(uname -s)  # Get the OS type
+
+  # Create a formatted output
+  echo "Terminal: $terminal_info\nOS Type: $os_info"
+}
+
 # Check if the model exists, if not, pull it
 if ! check_model_exists; then
   pull_model
 fi
 
-#tool_calls=(
-#  '{"function":{"name":"execute_shell_command","arguments":{"command":"echo LOL 1>&2; exit 1 "}}}'
-#)
-#apply_tool_calls "${tool_calls[@]}"
-#exit
 # Call the appropriate function based on tool usage
 if [ "$USE_TOOL" -eq 1 ]; then
+   escaped_system_prompt=$(echo "$SYSTEM_PROMPT_TOOL_CONTEXT\n\nSystem Info:\n$(gather_system_info)\n\nUser request\n:$PROMPT" | jq -Rsa .)
    tool_calls=(
      '{"function":{"name":"generate","arguments":{"prompt":"Create a concise title and subtitle that summarize the following task: '$PROMPT'"}}}'
      '{"function":{"name":"say","arguments":{"message":"$SHELLM_PREVIOUS"}}}'
-     '{"function":{"name":"generate","arguments":{"prompt":"Mirror and interpret the request and briefly state that you will proceed to work on a plan without giving details. Task: '$PROMPT'"}}}'
-     '{"function":{"name":"say","arguments":{"message":"$SHELLM_PREVIOUS"}}}'
-     '{"function":{"name":"generate","arguments":{"prompt":"Prepare concise instructions for a tool-calling AI agent. Summarize the context and outline a high-level strategy to address the following request without detailing specific tools: '$PROMPT'"}}}'
+     '{"function":{"name":"generate","arguments":{"prompt":'$escaped_system_prompt'}}}'
      '{"function":{"name":"say","arguments":{"message":"$SHELLM_PREVIOUS"}}}'
    )
 
